import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";
import { ProgressBar } from "@/components/ui/progress-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProgressBar />
        <nav className="flex items-center justify-center gap-4 border border-gray-200 py-4">
          <Link href="/">Home</Link>
          <Link href="/signin">Sign In</Link>
          <Link href="/signup">Sign Up</Link>
          <Link href="/dashboard">Dashboard</Link>
        </nav>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
